%heatMap_inactive_all_individual takes the heatmaps generated by heatMap_inactive and
%generates 4 figures for publication.
%Check heatMap_inactive.m to plot logarithmic heatmap.
%Labels font = 12

clear;
clc;

%Read the four _longform datasets. They include the position of inactive
%nuclei.
traces_es1n_es2gt = readmatrix('./singleTraceFits_Heatmaps/singleTraceFits_Stripe_longform_es1n_es2gt');
traces_es1wt_es2gt = readmatrix('./singleTraceFits_Heatmaps/singleTraceFits_Stripe_longform_es1wt_es2gt');
traces_es1n_es2wt = readmatrix('./singleTraceFits_Heatmaps/singleTraceFits_Stripe_longform_es1n_es2wt');
traces_es1wt_es2wt = readmatrix('./singleTraceFits_Heatmaps/singleTraceFits_Stripe_longform_es1wt_es2wt');

% titulo = 'eveS1\Delta-eveS2Gt';
% titulo = 'eveS1wt-eveS2Gt';
% titulo = 'eveS1\Delta-eveS2wt';
% titulo = 'eveS1wt-eveS2wt';

OuterPos = [0 0 18 8]; %Size of figures in centimeters

%%%%
f1 = figure(1);
f1.Units = 'centimeters';
f1.OuterPosition = OuterPos; %figure size in centimeters

titulo = 'Wild-type';
plttxt = titulo;
h1 = heatMap_inactive(traces_es1wt_es2wt, plttxt);
h1.Title = plttxt;

h1.XLabel = 'Fraction of Embryo Length';
h1.YLabel = 'Time in nc14 (min)';

print(gcf,'heatmaps_Wild-type.png','-dpng','-r800'); 

close(f1)

%%%%
f2 = figure(2);
f2.Units = 'centimeters';
f2.OuterPosition = OuterPos; %tiled figure size in centimeters

titulo = 'eveS1wt-eveS2Gt';
plttxt = strcat(titulo,'^{-}');
h2 = heatMap_inactive(traces_es1wt_es2gt, plttxt);
h2.Title = plttxt;

h2.XLabel = 'Fraction of Embryo Length';
h2.YLabel = 'Time in nc14 (min)';

print(gcf,'heatmaps_eveS1wt_eveS2Gt.png','-dpng','-r800'); 

close(f2)

%%%%
f3 = figure(3);
f3.Units = 'centimeters';
f3.OuterPosition = OuterPos; %tiled figure size in centimeters

titulo = 'eveS1\Delta-eveS2wt';
plttxt = titulo;
h3 = heatMap_inactive(traces_es1n_es2wt, plttxt);
h3.Title = plttxt;

h3.XLabel = 'Fraction of Embryo Length';
h3.YLabel = 'Time in nc14 (min)';

print(gcf,'heatmaps_es1n_es2wt.png','-dpng','-r800'); 

close(f3)

%%%%
f4 = figure(4);
f4.Units = 'centimeters';
f4.OuterPosition = OuterPos; %tiled figure size in centimeters

titulo = 'eveS1\Delta-eveS2Gt';
plttxt = strcat(titulo,'^{-}');
h4 = heatMap_inactive(traces_es1n_es2gt, plttxt);
h4.Title = plttxt;

h4.XLabel = 'Fraction of Embryo Length';
h4.YLabel = 'Time in nc14 (min)';

print(gcf,'heatmaps_es1n_es2gt.png','-dpng','-r800'); 

close(f4)
